### ISSUE TITLE
link

### ISSUE THREAD

**Issue by inyourface34456** [Nakul-Ardeshana/Bookmarklets#1]
The [strange link](https://r8---sn-gwpa-cvhz.googlevideo.com/videoplayback?expire=1567385238&amp;ei=NhJsXfr9MJms1gLe36SoCg&amp;ip=85.17.65.210&amp;id=o-AHg1zgcd38yqr96SfOV2NFX60ItOxPuJruI58FrqxBxD&amp;itag=18&amp;source=youtube&amp;requiressl=yes&amp;mime=video%2Fmp4&amp;gir=yes&amp;clen=15948801&amp;ratebypass=y) does not work. It gave me a 403 error.  
![image](https://user-images.githubusercontent.com/62214409/114711839-6a5beb80-9cfd-11eb-8bfe-20bb8351ec78.png)
If you own the content, please make it accessible to us.

**Comment by Nakul-Ardeshana** [comment]
yea I forgot to edit out the non-bookmarklets sorry!
and I think some are outdated, I am currently not active in tis repo 
so just delete the bookmarklet that does not work

**Comment by Nakul-Ardeshana** [comment]
also that link is for downloading a YouTube video (creator:-angry prash)
I don't know why I bookmarked it (tis is not my video ok so no copyright claims 😄😆)

**Comment by Nakul-Ardeshana** [comment]
i have one more script for replacing the current tab with another tab (which i made)
`javascript:location.replace('https://www.'+prompt('website url?'));`

you have to answer the prompt with a website url without 'https://www.'

tis is for a situation like tis:
you opened a game tab(let's say 1v1.lol)
and you want to remove it from 'control+shift+t'
you use my bookmarklet and poof the website disappears from 'control+shift+t'(tis does not work on stuff from chrome like chrome://history and etc)

**Comment by Nakul-Ardeshana** [comment]
also why did u use my bookmarklets!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 👿
